In [1]:
import numpy as np 

In [8]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print (v1)
print (v2)
print (v1+v2)
print (v1*v2)
dotProduct = np.dot(v1,v2)
print (dotProduct)
magnitude = np.linalg.norm(v1) 
print (magnitude) #magnitude also called norm 

[1 2 3]
[4 5 6]
[5 7 9]
[ 4 10 18]
32
3.7416573867739413


In [20]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
matrix2 = np.array([[7,8,9],[10,11,12]])
print()
print(matrix2)
print()
print(matrix - matrix2)
print()
#transpose.matrix.T

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

[[-6 -6 -6]
 [-6 -6 -6]]



In [23]:
#2x+3y = 5       4x-y =3
#([[2,3],[4,-1]])([[x],[y]])=([[5],[-3])
A = np.array([[2,3],[4,-1]])
b = np.array([5,3])
x = np.linalg.solve(A,b)
print(x)

[1. 1.]


In [29]:
#eigenvalue stuff 

A = np.array([[2,1],[1,2]])
e_value, e_vectors = np.linalg.eig(A)   #eig returns two things 
print("eiganvalue: ", e_value)
print("eiganvector: ", e_vectors)
print()

# inverse of a matrix 

A = np.array([[4,7],[2,6]])
A_inverse = np.linalg.inv(A)
print(A_inverse)
print()

identity = np.dot(A, A_inverse)
print(identity)
# 1 0 0
# 0 1 0
# 0 0 1

eiganvalue:  [3. 1.]
eiganvector:  [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

[[ 0.6 -0.7]
 [-0.2  0.4]]

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [30]:
#singular value decomposition 

A = np.array([[1,2],[3,4],[5,6]])
U, sigma, Vt = np.linalg.svd(A)
print(U)
print()
print(sigma)
print()
print(Vt)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

[9.52551809 0.51430058]

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
